/**
 * TORBIT - Ledger Export Integration
 * 
 * Includes ledger snapshot in export bundles for compliance.
 */

import type { IntegrationLedger } from './types'
import { exportLedger, getLedger } from './index'

/**
 * Filename for ledger in export bundles
 */
export const LEDGER_EXPORT_FILENAME = '.integrations/audit-ledger.json'

/**
 * Generate ledger content for export bundle
 */
export async function generateLedgerExportContent(): Promise<string | null> {
  const ledger = getLedger()
  
  if (!ledger || ledger.entryCount === 0) {
    return null
  }
  
  const exportData = await exportLedger(ledger)
  return JSON.stringify(exportData, null, 2)
}

/**
 * Generate a compliance summary for the export
 */
export function generateComplianceSummary(ledger: IntegrationLedger): {
  totalEvents: number
  governanceEvents: number
  consentEvents: number
  healthEvents: number
  remediationEvents: number
  exportEvents: number
  integrations: string[]
  dateRange: { from: string; to: string }
} {
  const entries = ledger.entries
  
  // Count by category
  const governanceEvents = entries.filter(
    (e) => e.event.includes('STRATEGIST') || e.event.includes('AUDITOR')
  ).length
  
  const consentEvents = entries.filter(
    (e) => e.event.includes('CONSENT')
  ).length
  
  const healthEvents = entries.filter(
    (e) => e.event.includes('HEALTH') || e.event.includes('DRIFT') || e.event.includes('DEPRECATION')
  ).length
  
  const remediationEvents = entries.filter(
    (e) => e.event.includes('FIX')
  ).length
  
  const exportEvents = entries.filter(
    (e) => e.event.includes('EXPORT') || e.event.includes('DEPLOY')
  ).length
  
  // Get unique integrations
  const integrations = [...new Set(entries.map((e) => e.integration))]
  
  // Get date range
  const timestamps = entries.map((e) => e.timestamp)
  const from = timestamps.length > 0 ? timestamps[0] : ledger.createdAt
  const to = timestamps.length > 0 ? timestamps[timestamps.length - 1] : ledger.createdAt
  
  return {
    totalEvents: ledger.entryCount,
    governanceEvents,
    consentEvents,
    healthEvents,
    remediationEvents,
    exportEvents,
    integrations,
    dateRange: { from, to },
  }
}

/**
 * Generate human-readable compliance report
 */
export function generateComplianceReport(ledger: IntegrationLedger): string {
  const summary = generateComplianceSummary(ledger)
  
  const lines = [
    '# TORBIT Integration Audit Report',
    '',
    '## Summary',
    '',
    `- **Project ID:** ${ledger.projectId}`,
    `- **Report Generated:** ${new Date().toISOString()}`,
    `- **Ledger Created:** ${ledger.createdAt}`,
    `- **Last Updated:** ${ledger.lastUpdated}`,
    '',
    '## Event Statistics',
    '',
    `| Category | Count |`,
    `|----------|-------|`,
    `| Total Events | ${summary.totalEvents} |`,
    `| Governance (Strategist/Auditor) | ${summary.governanceEvents} |`,
    `| User Consent | ${summary.consentEvents} |`,
    `| Health Checks | ${summary.healthEvents} |`,
    `| Remediation (Fixes) | ${summary.remediationEvents} |`,
    `| Export/Deploy | ${summary.exportEvents} |`,
    '',
    '## Integrations',
    '',
    summary.integrations.length > 0
      ? summary.integrations.map((i) => `- ${i}`).join('\n')
      : '_No integrations tracked_',
    '',
    '## Date Range',
    '',
    `- **First Event:** ${summary.dateRange.from}`,
    `- **Last Event:** ${summary.dateRange.to}`,
    '',
    '---',
    '',
    '_This report was automatically generated by TORBIT._',
    '_The complete audit ledger is available in `.integrations/audit-ledger.json`._',
  ]
  
  return lines.join('\n')
}

/**
 * Files to include in export bundle for compliance
 */
export async function getComplianceFiles(): Promise<{
  path: string
  content: string
}[]> {
  const ledger = getLedger()
  
  if (!ledger || ledger.entryCount === 0) {
    return []
  }
  
  const files: { path: string; content: string }[] = []
  
  // Add the full ledger export
  const ledgerContent = await generateLedgerExportContent()
  if (ledgerContent) {
    files.push({
      path: LEDGER_EXPORT_FILENAME,
      content: ledgerContent,
    })
  }
  
  // Add the human-readable report
  files.push({
    path: '.integrations/AUDIT_REPORT.md',
    content: generateComplianceReport(ledger),
  })
  
  return files
}
