/**
 * TORBIT Mobile - Export Service
 * Generates Xcode-ready export bundles
 */

import type { MobileCapabilities, MobileProjectConfig } from './types'

// ============================================
// Export Bundle Types
// ============================================

export interface ExportBundle {
  files: ExportFile[]
  metadata: ExportMetadata
}

export interface ExportFile {
  path: string
  content: string
}

export interface ExportMetadata {
  appName: string
  bundleId: string
  version: string
  buildNumber: number
  platforms: string[]
  capabilities: string[]
  exportedAt: string
  torbitVersion: string
}

// ============================================
// Generate Export Bundle
// ============================================

export function generateExportBundle(
  projectFiles: ExportFile[],
  config: MobileProjectConfig
): ExportBundle {
  const files: ExportFile[] = []
  
  // 1. Add all project files
  projectFiles.forEach(file => {
    files.push({
      path: file.path,
      content: file.content,
    })
  })
  
  // 2. Add README-SIGNING.md
  files.push({
    path: 'README-SIGNING.md',
    content: generateSigningReadme(config),
  })
  
  // 3. Add SUBMISSION-CHECKLIST.md
  files.push({
    path: 'SUBMISSION-CHECKLIST.md',
    content: generateSubmissionChecklist(config),
  })
  
  // 4. Add APP-METADATA.json
  const metadata: ExportMetadata = {
    appName: config.appName,
    bundleId: config.bundleId,
    version: config.version,
    buildNumber: config.buildNumber,
    platforms: config.platforms,
    capabilities: Object.entries(config.capabilities)
      .filter(([_, enabled]) => enabled)
      .map(([cap]) => cap),
    exportedAt: new Date().toISOString(),
    torbitVersion: '1.0.0',
  }
  
  files.push({
    path: 'APP-METADATA.json',
    content: JSON.stringify(metadata, null, 2),
  })
  
  // 5. Add .env.example
  files.push({
    path: '.env.example',
    content: generateEnvExample(config),
  })
  
  return { files, metadata }
}

// ============================================
// README-SIGNING.md Generator
// ============================================

function generateSigningReadme(config: MobileProjectConfig): string {
  return `# ${config.appName} - iOS Signing Guide

## Prerequisites

- **macOS** with Xcode 15+ installed
- **Apple Developer Account** (free or paid)
- **Node.js 18+** and npm installed

---

## Step 1: Install Dependencies

\`\`\`bash
# Install npm dependencies
npm install

# Install iOS dependencies
npx expo prebuild --platform ios
cd ios && pod install && cd ..
\`\`\`

---

## Step 2: Open in Xcode

\`\`\`bash
open ios/${config.bundleId.split('.').pop() || 'app'}.xcworkspace
\`\`\`

> ⚠️ Always open the **.xcworkspace** file, not .xcodeproj

---

## Step 3: Configure Signing

1. Select the project in the left sidebar
2. Select the main target (not "Tests")
3. Go to **Signing & Capabilities** tab
4. Check **"Automatically manage signing"**
5. Select your **Team** from the dropdown
6. Update **Bundle Identifier** to your own (e.g., \`com.yourcompany.${config.bundleId.split('.').pop()}\`)

---

## Step 4: Build & Run

### Simulator
1. Select a simulator from the device dropdown (e.g., "iPhone 15 Pro")
2. Press **⌘ + R** or click the Play button

### Physical Device
1. Connect your iPhone via USB
2. Trust your computer on the device
3. Select your device from the dropdown
4. Press **⌘ + R**

> First build on device requires your Apple ID to be trusted in Settings → General → Device Management

---

## Step 5: Archive for App Store

1. Select **"Any iOS Device (arm64)"** as the build target
2. Go to **Product → Archive**
3. Once complete, the Organizer window opens
4. Click **"Distribute App"**
5. Follow the prompts for App Store Connect

---

## Troubleshooting

### "No signing certificate found"
→ Sign in to Xcode with your Apple ID (Xcode → Settings → Accounts)

### "Bundle ID is not available"
→ Change the Bundle Identifier to something unique

### "Pod install failed"
\`\`\`bash
cd ios
pod deintegrate
pod install --repo-update
\`\`\`

### "Build failed with module errors"
\`\`\`bash
cd ios
rm -rf Pods Podfile.lock
pod install
\`\`\`

---

## Need Help?

- [Expo iOS Deployment Guide](https://docs.expo.dev/build/setup/)
- [Apple Developer Documentation](https://developer.apple.com/documentation/)
- [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/)

---

*Generated by TORBIT on ${new Date().toLocaleDateString()}*
`
}

// ============================================
// SUBMISSION-CHECKLIST.md Generator
// ============================================

function generateSubmissionChecklist(config: MobileProjectConfig): string {
  const enabledCapabilities = Object.entries(config.capabilities)
    .filter(([_, enabled]) => enabled)
    .map(([cap]) => cap as keyof MobileCapabilities)
  
  let checklist = `# ${config.appName} - App Store Submission Checklist

## App Information

- **App Name:** ${config.appName}
- **Bundle ID:** ${config.bundleId}
- **Version:** ${config.version}
- **Build Number:** ${config.buildNumber}
- **Minimum iOS:** ${config.minIosVersion}

---

## Pre-Submission Requirements

### ✅ Apple Developer Account
- [ ] Enrolled in Apple Developer Program ($99/year for App Store)
- [ ] App ID created in Apple Developer Portal
- [ ] Certificates and provisioning profiles configured

### ✅ App Store Connect Setup
- [ ] App created in App Store Connect
- [ ] App Information completed (name, subtitle, category)
- [ ] Pricing and availability configured
- [ ] App Privacy policy URL added

### ✅ Required Assets
- [ ] App Icon (1024x1024, no alpha channel)
- [ ] Screenshots for required device sizes:
  - [ ] iPhone 6.7" (1290 x 2796)
  - [ ] iPhone 6.5" (1284 x 2778)
  - [ ] iPhone 5.5" (1242 x 2208)
- [ ] App Preview videos (optional but recommended)

---

## Privacy & Permissions

`

  // Add capability-specific requirements
  if (enabledCapabilities.includes('camera')) {
    checklist += `### 📷 Camera Usage
- [ ] Added \`NSCameraUsageDescription\` in Info.plist
- [ ] Added \`NSPhotoLibraryUsageDescription\` in Info.plist
- [ ] Explain camera use in App Privacy section

`
  }

  if (enabledCapabilities.includes('location')) {
    checklist += `### 📍 Location Services
- [ ] Added \`NSLocationWhenInUseUsageDescription\` in Info.plist
- [ ] Added \`NSLocationAlwaysUsageDescription\` if using background location
- [ ] Justify location use in App Review notes

`
  }

  if (enabledCapabilities.includes('push')) {
    checklist += `### 🔔 Push Notifications
- [ ] APNs Key created in Apple Developer Portal
- [ ] Push notification capability enabled in Xcode
- [ ] Backend configured to send push notifications

`
  }

  if (enabledCapabilities.includes('biometrics')) {
    checklist += `### 🔐 Face ID / Touch ID
- [ ] Added \`NSFaceIDUsageDescription\` in Info.plist
- [ ] Provide fallback authentication method

`
  }

  if (enabledCapabilities.includes('payments')) {
    checklist += `### 💳 In-App Purchases
- [ ] In-App Purchase capability enabled
- [ ] Products created in App Store Connect
- [ ] Sandbox testing completed
- [ ] Tax and banking information configured
- [ ] Review App Store Guidelines 3.1 (Payments)

`
  }

  if (enabledCapabilities.includes('auth')) {
    checklist += `### 🔑 Authentication
- [ ] Privacy Policy URL provided
- [ ] Account deletion functionality implemented (required)
- [ ] Sign in with Apple implemented (if using social login)

`
  }

  checklist += `---

## App Review Preparation

### ✅ Review Guidelines Compliance
- [ ] Read [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/)
- [ ] No placeholder content or "lorem ipsum"
- [ ] All features functional and complete
- [ ] No references to other platforms (Android, etc.)

### ✅ Demo Account (if applicable)
- [ ] Provide test account credentials in App Review notes
- [ ] Ensure test account has access to all features

### ✅ Review Notes
- [ ] Explain any non-obvious functionality
- [ ] Provide context for any permission requests
- [ ] Include any special instructions for reviewers

---

## Final Checks

- [ ] Tested on physical device
- [ ] All analytics and crash reporting configured
- [ ] No debug code or test servers in production
- [ ] Version and build numbers incremented
- [ ] Archive builds successfully
- [ ] Validated in Xcode Organizer

---

## Submission

1. Archive the app in Xcode (Product → Archive)
2. Validate the archive in Organizer
3. Upload to App Store Connect
4. Complete App Store listing
5. Submit for Review

---

*Generated by TORBIT on ${new Date().toLocaleDateString()}*
`

  return checklist
}

// ============================================
// .env.example Generator
// ============================================

function generateEnvExample(config: MobileProjectConfig): string {
  let env = `# ${config.appName} - Environment Variables
# Copy this file to .env and fill in your values

# App Configuration
EXPO_PUBLIC_APP_NAME="${config.appName}"
EXPO_PUBLIC_BUNDLE_ID="${config.bundleId}"

`

  const capabilities = config.capabilities

  if (capabilities.auth) {
    env += `# Authentication
# EXPO_PUBLIC_AUTH_PROVIDER=clerk|auth0|supabase
# EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_xxx
# EXPO_PUBLIC_SUPABASE_URL=https://xxx.supabase.co
# EXPO_PUBLIC_SUPABASE_ANON_KEY=xxx

`
  }

  if (capabilities.push) {
    env += `# Push Notifications
# EXPO_PUBLIC_PUSH_PROJECT_ID=xxx

`
  }

  if (capabilities.payments) {
    env += `# In-App Purchases
# Revenue Cat, or native StoreKit
# EXPO_PUBLIC_REVENUECAT_API_KEY=xxx

`
  }

  if (capabilities.storage) {
    env += `# Cloud Storage
# EXPO_PUBLIC_STORAGE_BUCKET=xxx

`
  }

  env += `# API Configuration
# EXPO_PUBLIC_API_URL=https://api.example.com
`

  return env
}

// ============================================
// Create ZIP (Browser-compatible)
// ============================================

export async function createExportZip(bundle: ExportBundle): Promise<Blob> {
  // We'll use JSZip for this - it works in both browser and Node
  const { default: JSZip } = await import('jszip')
  
  const zip = new JSZip()
  
  // Add all files to the zip
  bundle.files.forEach(file => {
    zip.file(file.path, file.content)
  })
  
  // Generate the zip blob
  const blob = await zip.generateAsync({ 
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  })
  
  return blob
}

// ============================================
// Trigger Download
// ============================================

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
