/**
 * TORBIT - Attestation Generator
 * 
 * Generates human-readable, signed attestation statements.
 * "This build was exported on..."
 */

import type { AttestationFile, AttestationData } from './types'
import type { EnvironmentName } from '../environments/types'

// ============================================
// ATTESTATION GENERATOR
// ============================================

/**
 * Generate an attestation file for export
 */
export function generateAttestation(data: AttestationData): AttestationFile {
  const statement = generateStatement(data)
  const hash = generateHash(JSON.stringify(data))
  
  return {
    statement,
    data,
    generatedAt: new Date().toISOString(),
    hash,
  }
}

/**
 * Generate human-readable attestation statement
 */
function generateStatement(data: AttestationData): string {
  const lines = [
    '═══════════════════════════════════════════════════════════════',
    '                    TORBIT EXPORT ATTESTATION                   ',
    '═══════════════════════════════════════════════════════════════',
    '',
    `This build was exported on ${formatDate(data.exportDate)}.`,
    '',
    '┌─────────────────────────────────────────────────────────────┐',
    '│ ENVIRONMENT & POLICY                                        │',
    '├─────────────────────────────────────────────────────────────┤',
    `│ Environment:        ${padRight(data.environment.toUpperCase(), 38)}│`,
    `│ Policy:             ${padRight(data.policyName, 38)}│`,
    '└─────────────────────────────────────────────────────────────┘',
    '',
    '┌─────────────────────────────────────────────────────────────┐',
    '│ COMPLIANCE STATUS                                           │',
    '├─────────────────────────────────────────────────────────────┤',
    `│ Integration Health: ${padRight(formatStatus(data.integrationHealth), 38)}│`,
    `│ Version Drift:      ${padRight(data.driftStatus, 38)}│`,
    `│ Auditor:            ${padRight(formatStatus(data.auditorStatus), 38)}│`,
    `│ Strategist:         ${padRight(formatStatus(data.strategistStatus), 38)}│`,
    '└─────────────────────────────────────────────────────────────┘',
    '',
    '┌─────────────────────────────────────────────────────────────┐',
    '│ STATISTICS                                                  │',
    '├─────────────────────────────────────────────────────────────┤',
    `│ Integrations:       ${padRight(String(data.integrationCount), 38)}│`,
    `│ Ledger Entries:     ${padRight(String(data.ledgerEntryCount), 38)}│`,
    `│ Policy Violations:  ${padRight(String(data.policyViolations), 38)}│`,
    `│ Env Violations:     ${padRight(String(data.environmentViolations), 38)}│`,
    '└─────────────────────────────────────────────────────────────┘',
    '',
  ]
  
  // Add compliance verdict
  const isCompliant = 
    data.integrationHealth !== 'ERRORS' &&
    data.driftStatus === 'NONE' &&
    data.auditorStatus !== 'FAILED' &&
    data.policyViolations === 0 &&
    data.environmentViolations === 0
  
  if (isCompliant) {
    lines.push(
      '┌─────────────────────────────────────────────────────────────┐',
      '│                      ✓ COMPLIANT                            │',
      '│         This export meets all governance requirements.       │',
      '└─────────────────────────────────────────────────────────────┘'
    )
  } else {
    lines.push(
      '┌─────────────────────────────────────────────────────────────┐',
      '│                    ⚠ NON-COMPLIANT                          │',
      '│       This export has unresolved compliance issues.         │',
      '└─────────────────────────────────────────────────────────────┘'
    )
  }
  
  lines.push(
    '',
    '═══════════════════════════════════════════════════════════════',
    `Generated by TORBIT on ${new Date().toISOString()}`,
    '═══════════════════════════════════════════════════════════════'
  )
  
  return lines.join('\n')
}

// ============================================
// QUICK ATTESTATION
// ============================================

/**
 * Generate a quick attestation from current state
 */
export function generateQuickAttestation(
  environment: EnvironmentName,
  policyName: string,
  stats: {
    integrationCount: number
    ledgerEntryCount: number
    hasDrift: boolean
    hasHealthIssues: boolean
    auditorPassed: boolean
    strategistPassed: boolean
    policyViolations: number
    environmentViolations: number
  }
): AttestationFile {
  const data: AttestationData = {
    exportDate: new Date().toISOString(),
    environment,
    policyName,
    integrationHealth: stats.hasHealthIssues ? 'ERRORS' : 'CLEAN',
    driftStatus: stats.hasDrift ? 'DETECTED' : 'NONE',
    auditorStatus: stats.auditorPassed ? 'PASSED' : 'SKIPPED',
    strategistStatus: stats.strategistPassed ? 'PASSED' : 'SKIPPED',
    integrationCount: stats.integrationCount,
    ledgerEntryCount: stats.ledgerEntryCount,
    policyViolations: stats.policyViolations,
    environmentViolations: stats.environmentViolations,
  }
  
  return generateAttestation(data)
}

// ============================================
// UTILITIES
// ============================================

function formatDate(isoDate: string): string {
  const date = new Date(isoDate)
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  })
}

function formatStatus(status: string): string {
  const icons: Record<string, string> = {
    CLEAN: '✓ CLEAN',
    WARNINGS: '⚠ WARNINGS',
    ERRORS: '✗ ERRORS',
    PASSED: '✓ PASSED',
    FAILED: '✗ FAILED',
    SKIPPED: '○ SKIPPED',
    NONE: '✓ NONE',
    DETECTED: '⚠ DETECTED',
  }
  return icons[status] || status
}

function padRight(str: string, length: number): string {
  return str.padEnd(length)
}

/**
 * Generate a simple hash (for display purposes)
 * In production, use crypto.subtle.digest
 */
function generateHash(input: string): string {
  let hash = 0
  for (let i = 0; i < input.length; i++) {
    const char = input.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash
  }
  
  // Convert to hex-like string
  const hexHash = Math.abs(hash).toString(16).padStart(8, '0')
  return `sha256:${hexHash}${hexHash}${hexHash}${hexHash}`
}

/**
 * Serialize attestation to text file
 */
export function serializeAttestation(attestation: AttestationFile): string {
  return [
    attestation.statement,
    '',
    '───────────────────────────────────────────────────────────────',
    'ATTESTATION HASH',
    '───────────────────────────────────────────────────────────────',
    attestation.hash,
    '',
    'This hash can be used to verify the integrity of this attestation.',
    '───────────────────────────────────────────────────────────────',
  ].join('\n')
}
