import { describe, expect, it, vi } from "vitest";
import {
  auditIntegration,
  createIntegrationPlan,
  executeIntegrationPlan,
  runIntegrationFlow,
} from "./executor";

describe("integration executor quality gates", () => {
  it("uses manifest-backed fallback templates when explicit templates are absent", async () => {
    const planResult = createIntegrationPlan({
      integrationId: "sendgrid",
      platform: "web",
      providedSecrets: ["SENDGRID_API_KEY", "SENDGRID_FROM_EMAIL"],
    });

    expect(planResult.success).toBe(true);
    if (!planResult.plan) {
      throw new Error("expected a valid plan");
    }

    const installPackage = vi.fn().mockResolvedValue(undefined);
    const createFile = vi.fn().mockResolvedValue(undefined);

    const result = await executeIntegrationPlan({
      plan: planResult.plan,
      userConsented: true,
      installPackage,
      createFile,
      injectSecureEnv: vi.fn().mockResolvedValue(undefined),
    });

    expect(result.success).toBe(true);
    expect(result.error).toBeUndefined();
    expect(result.createdFiles.length).toBeGreaterThan(0);
    expect(Object.keys(result.createdFileContents).length).toBeGreaterThan(0);
    expect(result.createdFileContents["src/lib/email/sendgrid.ts"]).toContain("module scaffold");
    expect(createFile).toHaveBeenCalled();
    expect(installPackage).toHaveBeenCalled();
  });

  it("flags placeholder output during audit", async () => {
    const planResult = createIntegrationPlan({
      integrationId: "sendgrid",
      platform: "web",
      providedSecrets: ["SENDGRID_API_KEY", "SENDGRID_FROM_EMAIL"],
    });

    expect(planResult.success).toBe(true);
    if (!planResult.plan) {
      throw new Error("expected a valid plan");
    }

    const review = await auditIntegration({
      plan: planResult.plan,
      installedPackages: ["@sendgrid/mail@8.1.1"],
      createdFiles: ["src/lib/email/sendgrid.ts"],
      createdFileContents: {
        "src/lib/email/sendgrid.ts": `/**
 * src/lib/email/sendgrid.ts
 * Generated by TORBIT Integration System
 * Integration: sendgrid
 *
 * TODO: Implement this file
 */

export {};
`,
      },
      checkSecretLeakage: async () => false,
    });

    expect(review.verdict).toBe("FAILED");
    expect(review.issues).toContain("Placeholder template generated: src/lib/email/sendgrid.ts");
  });

  it("completes integration flow when fallback templates are available", async () => {
    const getStrategistReview = vi.fn();
    const getUserConsent = vi.fn().mockResolvedValue(true);
    const checkSecretLeakage = vi.fn().mockResolvedValue(false);

    const result = await runIntegrationFlow({
      integrationId: "sendgrid",
      platform: "web",
      providedSecrets: ["SENDGRID_API_KEY", "SENDGRID_FROM_EMAIL"],
      secretValues: {
        SENDGRID_API_KEY: "sg-key",
        SENDGRID_FROM_EMAIL: "noreply@example.com",
      },
      getStrategistReview,
      getUserConsent,
      installPackage: vi.fn().mockResolvedValue(undefined),
      createFile: vi.fn().mockResolvedValue(undefined),
      injectSecureEnv: vi.fn().mockResolvedValue(undefined),
      checkSecretLeakage,
    });

    expect(result.success).toBe(true);
    expect(result.error).toBeUndefined();
    expect(result.createdFiles.length).toBeGreaterThan(0);
    expect(getStrategistReview).not.toHaveBeenCalled();
    expect(checkSecretLeakage).toHaveBeenCalled();
  });
});
